export const questions = [
  "Should I be honest with you on here?",
  "Do you want kids eventually?",
  "Are you looking to date someone?",
  "Do you have trust issues?",
  "What's your favorite book?",
  "Opinion on birds?",
  "What color is your room?",
  "Your favorite part of your body?",
  "How many selfies do you take a day?",
  "Do you even like school?",
  "Can we be besties?",
  "Who's the last person you texted?",
  "Who was the last dude you texted?",
  "Craziest pickup line that worked?",
  "Favorite food?",
  "Uh, what did you eat for breakfast?",
  "How many kids do you want to have?",
  "One thing you can't survive without?",
  "How's your day going??!",
  "Who's your last Instagram search?",
  "Your worst personality characteristic?",
  "Do you even like school?",
  "When was your first kiss?",
  "Why doesn't my crush like me back? 😭",
  "Are you judgmental?",
  "Do you enjoy watching sports?",
  "What's your favorite type of sport to watch?",
  "Do you have a favorite sports team?",
  "Are you a morning or night jogger?",
  "What's your favorite type of exercise to do outdoors?",
  "Do you enjoy playing musical instruments?",
  "What's your favorite type of musical instrument?",
  "Do you like attending concerts?",
  "What's your favorite type of music to experience live?",
  "Are you a morning or night meditator?",
  "What's your favorite type of meditation?",
  "Do you enjoy stargazing?",
  "What's your favorite constellation?",
  "Are you a morning or night photographer?",
  "What's your favorite type of photography?",
  "Do you have a favorite photography subject?",
  "Are you a morning or night gamer?",
  "What's your favorite type of video game genre?",
  "Do you enjoy watching documentaries?",
  "What's your favorite documentary topic?",
  "Do you like to collect anything?",
  "What's your favorite item in your collection?",
  "Do you enjoy puzzles?",
  "What's your favorite type of puzzle?",
  "Are you a morning or night thinker?",
  "What's your favorite type of thought exercise?",
  "Do you have a favorite quote that inspires you?",
  "Are you a morning or night artist?",
  "What's your favorite type of art to create?",
  "Do you enjoy DIY projects?",
  "What's your favorite type of DIY project?",
  "Are you a morning or night explorer?",
  "What's your favorite type of place to explore?",
  "Do you enjoy gardening?",
  "What's your favorite type of plant?",
  "Are you a morning or night birdwatcher?",
  "What's your favorite bird?",
  "Do you have any favorite podcasts?",
  "What's your favorite podcast genre?",
  "Do you enjoy cooking?",
  "What's your favorite type of dish to prepare?",
  "Do you have any favorite TED Talks?",
  "What's your favorite TED Talk topic?",
  "Are you a morning or night learner?",
  "What's your favorite way to learn new things?",
  "Do you enjoy volunteering?",
  "What's your favorite cause to support?",
  "Are you a morning or night adventurer?",
  "What's your favorite type of adventure?",
  "Do you have any favorite board games?",
  "What's your strategy in your favorite board game?",
  "Do you enjoy attending festivals?",
  "What's your favorite type of festival?",
  "Are you a morning or night poet?",
  "What's your favorite type of poetry?",
  "Do you have any favorite jokes?",
  "What's your go-to joke to make people laugh?",
  "Are you a morning or night philosopher?",
  "What's your favorite philosophical concept?",
  "Do you enjoy astronomy?",
  "What's your favorite celestial body?",
  "Are you a morning or night painter?",
  "What's your favorite type of painting?",
  "Do you have a favorite artist?",
  "What's your favorite work of art?",
  "Are you a morning or night writer?",
  "What's your favorite genre of writing?",
  "Do you enjoy public speaking?",
  "What's your favorite topic to speak about?",
  "Are you a morning or night reader?",
  "What's your favorite genre of literature?",
  "Do you have a favorite book series?",
  "What's your favorite way to unwind after a long day?",
  "Do you enjoy attending workshops?",
  "What's your favorite type of workshop?",
  "Are you a morning or night dancer?",
  "What's your favorite type of dance?",
  "Do you have a favorite dance move?",
  "Are you a morning or night traveler?",
  "What's your favorite type of travel destination?",
  "Do you enjoy writing letters?",
  "What's your favorite type of letter to write?",
  "Are you a morning or night dreamer?",
  "What's your most memorable dream?",
  "Do you enjoy board games?",
  "What's your favorite strategy in board games?",
  "Do you have a favorite type of puzzle?",
  "What's your favorite type of puzzle to solve?",
  "Do you enjoy cooking?",
  "What's your favorite type of music?",
  "Are you a morning person or a night owl?",
  "What's your dream travel destination?",
  "Do you believe in love at first sight?",
  "How do you handle stress?",
  "What's your favorite movie genre?",
  "Do you prefer dogs or cats?",
  "What's your go-to karaoke song?",
  "Are you an introvert or extrovert?",
  "What's your favorite type of cuisine?",
  "Do you have any phobias?",
  "What's your favorite way to stay active?",
  "Do you have any hidden talents?",
  "What's your favorite childhood memory?",
  "Are you a coffee or tea person?",
  "What's the most adventurous thing you've done?",
  "Do you believe in fate?",
  "What's your spirit animal?",
  "What's your favorite TV show?",
  "Are you a planner or spontaneous?",
  "Do you enjoy outdoor activities?",
  "What's your biggest fear?",
  "What's your favorite season?",
  "Are you a beach or mountain person?",
  "Do you have any tattoos?",
  "What's your favorite type of dessert?",
  "Do you like attending live events (concerts, sports games, etc.)?",
  "What's your favorite board game?",
  "What's your favorite app on your phone?",
  "Are you a morning or night shower person?",
  "What's your favorite type of weather?",
  "Do you have a favorite quote?",
  "What's your biggest pet peeve?",
  "Do you believe in second chances?",
  "What's your favorite holiday?",
  "What's your dream job?",
  "Do you believe in aliens?",
  "What's your favorite hobby?",
  "What's your preferred mode of transportation?",
  "Do you enjoy camping?",
  "What's your favorite type of art?",
  "Are you a sports fan?",
  "What's your favorite type of workout?",
  "Do you enjoy gardening?",
  "What's your favorite type of flower?",
  "Do you prefer sweet or savory snacks?",
  "What's your favorite type of ice cream?",
  "Do you have a favorite childhood TV show?",
  "What's your favorite type of footwear?",
  "Do you enjoy DIY projects?",
  "What's your favorite type of cheese?",
  "Are you a morning or evening shower person?",
  "Do you enjoy attending weddings?",
  "What's your favorite type of fruit?",
  "Do you like to dance?",
  "What's your favorite type of dance?",
  "Do you enjoy museums?",
  "What's your favorite type of art?",
  "Are you a good swimmer?",
  "What's your favorite type of cocktail?",
  "Do you enjoy hiking?",
  "What's your favorite board game?",
  "Do you like to play video games?",
  "What's your favorite type of video game?",
  "Do you enjoy road trips?",
  "What's your favorite type of road trip snack?",
  "Are you a morning or night exerciser?",
  "What's your favorite type of exercise?",
  "Do you enjoy going to the gym?",
  "What's your favorite type of workout?",
  "Do you enjoy cooking?",
  "What's your favorite type of cuisine?",
  "Do you like to bake?",
  "What's your favorite type of baked good?",
  "Are you a good dancer?",
  "What's your favorite type of dance?",
  "Do you enjoy shopping?",
  "What's your favorite type of clothing?",
  "Do you enjoy going to the beach?",
  "What's your favorite type of beach activity?",
  "Are you a morning or night reader?",
  "What's your favorite type of book?",
  "Do you enjoy writing?",
  "What's your favorite type of writing?",
  "Are you a morning or night thinker?",
  "What's your favorite type of thought?",
  "Do you enjoy public speaking?",
  "What's your favorite type of public speaking?",
  "Are you a morning or night listener?",
  "What's your favorite type of music to listen to?",
  "Do you enjoy watching sports?",
  "What's your favorite type of sport to watch?",
  "Do you have a favorite sports team?",
  "Are you a morning or night jogger?",
  "What's your favorite type of exercise to do outdoors?",
  "Do you enjoy playing musical instruments?",
  "What's your favorite type of musical instrument?",
  "Do you like attending concerts?",
  "What's your favorite type of music to experience live?",
  "Are you a morning or night meditator?",
  "What's your favorite type of meditation?",
  "Do you enjoy stargazing?",
  "What's your favorite constellation?",
  "Are you a morning or night photographer?",
  "What's your favorite type of photography?",
  "Do you have a favorite photography subject?",
  "Are you a morning or night gamer?",
  "What's your favorite type of video game genre?",
  "Do you enjoy watching documentaries?",
  "What's your favorite documentary topic?",
  "Do you like to collect anything?",
  "What's your favorite item in your collection?",
  "Do you enjoy puzzles?",
  "What's your favorite type of puzzle?",
  "Are you a morning or night thinker?",
  "What's your favorite type of thought exercise?",
  "Do you have a favorite quote that inspires you?",
  "Are you a morning or night artist?",
  "What's your favorite type of art to create?",
  "Do you enjoy DIY projects?",
  "What's your favorite type of DIY project?",
  "Are you a morning or night explorer?",
  "What's your favorite type of place to explore?",
  "Do you enjoy gardening?",
  "What's your favorite type of plant?",
  "Are you a morning or night birdwatcher?",
  "What's your favorite bird?",
  "Do you have any favorite podcasts?",
  "What's your favorite podcast genre?",
  "Do you enjoy cooking?",
  "What's your favorite type of dish to prepare?",
  "Do you have any favorite TED Talks?",
  "What's your favorite TED Talk topic?",
  "Are you a morning or night learner?",
  "What's your favorite way to learn new things?",
  "Do you enjoy volunteering?",
  "What's your favorite cause to support?",
  "Are you a morning or night adventurer?",
  "What's your favorite type of adventure?",
  "Do you have any favorite board games?",
  "What's your strategy in your favorite board game?",
  "Do you enjoy attending festivals?",
  "What's your favorite type of festival?",
  "Are you a morning or night poet?",
  "What's your favorite type of poetry?",
  "Do you have any favorite jokes?",
  "What's your go-to joke to make people laugh?",
  "Are you a morning or night philosopher?",
  "What's your favorite philosophical concept?",
  "Do you enjoy astronomy?",
  "What's your favorite celestial body?",
  "Are you a morning or night painter?",
  "What's your favorite type of painting?",
  "Do you have a favorite artist?",
  "What's your favorite work of art?",
  "Are you a morning or night writer?",
  "What's your favorite genre of writing?",
  "Do you enjoy public speaking?",
  "What's your favorite topic to speak about?",
  "Are you a morning or night reader?",
  "What's your favorite genre of literature?",
  "Do you have a favorite book series?",
  "What's your favorite way to unwind after a long day?",
  "Do you enjoy attending workshops?",
  "What's your favorite type of workshop?",
  "Are you a morning or night dancer?",
  "What's your favorite type of dance?",
  "Do you have a favorite dance move?",
  "Are you a morning or night traveler?",
  "What's your favorite type of travel destination?",
  "Do you enjoy writing letters?",
  "What's your favorite type of letter to write?",
  "Are you a morning or night dreamer?",
  "What's your most memorable dream?",
  "Do you enjoy board games?",
  "What's your favorite strategy in board games?",
  "Do you have a favorite type of puzzle?",
  "What's your favorite type of puzzle to solve?",
];
